FROM debian:bullseye-slim

WORKDIR /app

# 复制二进制文件
COPY server /app/server
# 复制配置文件 (如果需要)
# COPY config.yaml /app/config.yaml

# 设置时区
RUN apt-get update && apt-get install -y ca-certificates tzdata && \
    ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone && \
    rm -rf /var/lib/apt/lists/*

EXPOSE 8080

RUN chmod +x /app/server

CMD ["./server"]
